name: Update gist with latest tweet
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: coderganesh/gist-bird@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: df699dbdc935ba86dc0f5d2c1c053b40
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_USER: gaaneshaha
